first_django_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('new_project/', include("new_project.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
]

new_project/urls.py
from django import views
from django.urls import path
from . import views

urlpatterns = [
    path("",views.index, name="index"),
    path("<str:name>",views.greet, name="greet"),
    path("vova",views.vova, name="vova")
]

newyear/urls.py
from django.urls import path
from . import views

app_name = "newyear"
urlpatterns =[path("", views.index, name="index")]
    

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

new_project/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

new_project/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "new_project/index.html")

def vova(request):
    return HttpResponse("Hello, Vova!")

def greet(request, name):
    return HttpResponse(f"Hello, {name.capitalize()}!")

newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.

def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.day == 1 and now.month == 1
    })

tasks/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django import forms
from django.shortcuts import render


class NewTaskForm(forms.Form):
    task=forms.CharField(label="New task")
    priority=forms.IntegerField(label="Priority", min_value=1, max_value=10)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks":request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
           task= form.cleaned_data["task"]
           request.session["tasks"] += [task]
           return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request,"tasks/add.html", {
                "form":form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

new_project/templates/new_project/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>hello</title>
</head>

<body>
    <h1>Hello, world!</h1>
</body>

</html>

newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'newyear/styles.css' %}" rel="stylesheet" />
    <title>Is New Year?</title>
</head>

<body>
    {% if newyear %}
    <h1>YES</h1>
    {% else %}
    <h1>NO</h1>
    {% endif %}
</body>

</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}
{% block body %}
<h1>Add task</h1>
<ul>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
</ul>
<a href="{% url 'tasks:index' %}">Tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Tasks</h1>
<ul>
    {% for task in tasks %}
    <li>{{task}}</li>
    {% empty %}
    <li>No tasks.</li>
    {% endfor %}
</ul>
<a href="{% url 'tasks:add' %}">Add a new task</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>

<body>

    {% block body %}

    {% endblock %}
</body>

</html>